{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Building a TV Frame\n",
    "\n",
    "> If you're not keen on reading through my design work, that's a bit of a shame, but I understand; we're busy people. Feel free to check out the [downloads at the bottom](#Downloads) of the article, though!\n",
    "\n",
    "Several years ago I built a weird looking desk that had a PC and TV built right in. It never progressed beyond 'usable prototype', and was eventually disassembled. The TV had been partially stripped down to fit nicely in the desk's surface, and the old parts were discarded.\n",
    "\n",
    "![](img/old_desk.jpg)\n",
    "\n",
    "Since the TV is still good, I want to design a frame and stand that will allow me to actually use it again.\n",
    "\n",
    "## Requirements\n",
    "\n",
    "The frame must meet the following criteria:\n",
    "\n",
    "* look decent\n",
    "* be of sound construction, meaning: all connections must be *tight* and secure.\n",
    "* cover the loose circuit board on the front\n",
    "* not obstruct any ports on the back of the TV\n",
    "* provide mounting points on the base for a simple stand\n",
    "* allow for standard TV mounting hardware to still fit on the back of the TV\n",
    "\n",
    "## Details and Images\n",
    "\n",
    "Before the design can properly begin, some measurements will be needed. I walked around the shop and discovered a half-used bundle of some interesting material. \n",
    "\n",
    "![](img/raw_material.jpg)\n",
    "\n",
    "After checking that it was actually OK to use a length or two of this (it was), I pulled one length out and measured. The dimensions are shown below.\n",
    "\n",
    "<center>![](img/profile.svg)</center>\n",
    "\n",
    "Conveniently, there is a *work in progress* dxf importer for CadQuery that should make it much simpler to work with 2D objects.\n",
    "\n",
    "So, I made a **.dxf** file very similar to the above SVG, and imported it to create the tube that I'll use to define all of the tv frame's parts."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# make a simple sample piece \n",
    "# to try out the dxf import function\n",
    "sample_tube = (cq.Workplane('XY')\n",
    "               .workplane(offset=-1)\n",
    "               .dxf('downloads/profile.dxf')\n",
    "               .extrude(2)\n",
    "              )\n",
    "\n",
    "show_object(sample_tube)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Alright, it works! Now I can work on the actual design.\n",
    "\n",
    "## Parts Plan\n",
    "\n",
    "This design is going to be a bit more advanced than my [ipad_stand](https://rustyvermeer.github.io/design/ipad_stand/index.html), so I've got a mental picture in mind that will take a few different parts:\n",
    "\n",
    "* outer frame composed of:\n",
    "    * horizontal bar bottom (1x)\n",
    "    * horizontal bar top (1x)\n",
    "    * vertical bar (2x)\n",
    "* inner frame composed of:\n",
    "    * horizontal bar (2x)\n",
    "    * vertical bar (2x)\n",
    "* back lock bar (2x)\n",
    "* stand bar (2x)\n",
    "\n",
    "Naming things is, generally speaking, a difficult thing to do. As such, it's much more sensible to *see* the parts than it is to rely solely on names. The next steps will be defining the CadQuery code to generate all of the parts in the list.    "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Outer Frame Horizontals\n",
    "\n",
    "The horizontal frame pieces are identical, with a small exception for the bottom bar: two holes are cut in order to provide a mounting location for the legs.\n",
    "\n",
    "## Outer Horizontal Top"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "L = 31.6772 # comes from width of scrn + offset due to tube dims\n",
    "tap_01875 = 0.1495\n",
    "\n",
    "outer_h_top = (cq.Workplane('XY')\n",
    "               .workplane(offset=-L/2.0)\n",
    "               .dxf('downloads/profile.dxf')\n",
    "               .extrude(L)\n",
    "               # holes on top face near edge\n",
    "               # will be tapped with 3/16 bolt thread\n",
    "               # used to mount inner frame tube\n",
    "               .faces('>Y').workplane()\n",
    "               .pushPoints([(-0.5,  13.3386),\n",
    "                            (-0.5, -13.3386),\n",
    "                            (-0.5,  6.6693),\n",
    "                            (-0.5, -6.6693),\n",
    "                            (-0.5, 0.0),])\n",
    "               .hole(tap_01875, depth=0.08)\n",
    "               # holes centered on back face\n",
    "               # 2 pairs of 3/16 tapped holes\n",
    "               # will mount back 'lock bar' tubes\n",
    "               .faces('<X').workplane()\n",
    "               .pushPoints([(0.0, 6.8386),\n",
    "                            (0.0, 7.8386),\n",
    "                            (0.0, -6.8386),\n",
    "                            (0.0, -7.8386)])\n",
    "               .hole(tap_01875, depth=0.08)\n",
    "               # Cut the tube ends to create a 'dovetail'\n",
    "               # joint to hold the vertical tubes in place\n",
    "               # back left\n",
    "               .faces('>Y').workplane()\n",
    "               .moveTo(0.425, 15.3386)\n",
    "               .polyline([(0.425, 15.4086),\n",
    "                         (0.5, 15.839),\n",
    "                         (0.75, 15.839),\n",
    "                         (0.75, 15.3386)]).close()\n",
    "               .cutThruAll()\n",
    "               # front left\n",
    "               .faces('>Y').workplane(centerOption='CenterOfBoundBox')\n",
    "               .moveTo(-0.425, 15.3386)\n",
    "               .polyline([(-0.425, 15.4086),\n",
    "                         (-0.5, 15.839),\n",
    "                         (-0.75, 15.839),\n",
    "                         (-0.75, 15.3386)]).close()\n",
    "               .cutThruAll()\n",
    "               # back right\n",
    "               .faces('>Y').workplane(centerOption='CenterOfBoundBox')\n",
    "               .moveTo(0.425, -15.3386)\n",
    "               .polyline([(0.425, -15.4086),\n",
    "                         (0.5, -15.839),\n",
    "                         (0.75, -15.839),\n",
    "                         (0.75, -15.3386)]).close()\n",
    "               .cutThruAll()\n",
    "               # front right\n",
    "               .faces('>Y').workplane(centerOption='CenterOfBoundBox')\n",
    "               .moveTo(-0.425, -15.3386)\n",
    "               .polyline([(-0.425, -15.4086),\n",
    "                         (-0.5, -15.839),\n",
    "                         (-0.75, -15.839),\n",
    "                         (-0.75, -15.3386)]).close()\n",
    "               .cutThruAll()\n",
    "              )\n",
    "\n",
    "show_object(outer_h_top)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Outer Horizontal Bottom"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "tap_025 = 0.201\n",
    "\n",
    "outer_h_bottom = (outer_h_top\n",
    "                  .faces('<Y').workplane(centerOption='CenterOfBoundBox')\n",
    "                  .pushPoints([(0.0,  7.3386),\n",
    "                               (0.0, -7.3386)])\n",
    "                  .hole(tap_01875, depth=0.08)\n",
    "                 )\n",
    "\n",
    "show_object(outer_h_bottom)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Outer Verticals"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "L = 19.6693 # comes from height of scrn + offset due to tube dims\n",
    "tap_01875 = 0.1495\n",
    "\n",
    "outer_v = (cq.Workplane('XY')\n",
    "               .workplane(offset=-L/2.0)\n",
    "               .dxf('downloads/profile.dxf')\n",
    "               .extrude(L)\n",
    "               # holes on top face near edge\n",
    "               # will be tapped with 3/16 bolt thread\n",
    "               # used to mount inner frame tube\n",
    "               .faces('<Y').workplane()\n",
    "               .pushPoints([(-0.5,  8.8507),\n",
    "                            (-0.5, -8.8507),\n",
    "                            (-0.5,  4.4173),\n",
    "                            (-0.5, -4.4173),\n",
    "                            (-0.5, 0.0),])\n",
    "               .hole(tap_01875, depth=0.08)\n",
    "               # Cut the tube ends to create the\n",
    "               # 'dovetail' slot\n",
    "               # left\n",
    "               .faces('>Z').workplane(centerOption='CenterOfBoundBox')\n",
    "               .moveTo(0.0, -0.135).rect(0.85, 0.25, centered=True)\n",
    "               .cutBlind(-0.5, clean=True)\n",
    "               .faces('>Z').workplane(centerOption='CenterOfBoundBox')\n",
    "               .moveTo(0.0, 0.135).rect(1.0, 0.25, centered=True)\n",
    "               .cutBlind(-0.5, clean=True)\n",
    "               # right\n",
    "               .faces('<Z').workplane(centerOption='CenterOfBoundBox')\n",
    "               .moveTo(0.0, 0.135).rect(0.85, 0.25, centered=True)\n",
    "               .cutBlind(-0.5, clean=True)\n",
    "               .faces('<Z').workplane(centerOption='CenterOfBoundBox')\n",
    "               .moveTo(0.0, -0.135).rect(1.0, 0.25, centered=True)\n",
    "               .cutBlind(-0.5, clean=True)\n",
    "              )\n",
    "\n",
    "show_object(outer_v)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Inner Frame Horizontals and Verticals\n",
    "\n",
    "The inner frame components are identically designed. The horizontal bars are equivalent, as are the vertical bars. The only difference between the verticals and horizontals is the length. As such, the following code is parametric according to L, the tube's total length."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "L = 27.6772 # horizontals\n",
    "# L = 18.6693 # verticals\n",
    "tap_01875 = 0.1495\n",
    "\n",
    "pnts = [(0.0, 0.0),\n",
    "        (0.0,  (L/2.0 - 0.5) ),\n",
    "        (0.0, -(L/2.0 - 0.5) ),\n",
    "        (0.0,  (L/2.0 - 0.5)/2.0 ),\n",
    "        (0.0, -(L/2.0 - 0.5)/2.0 )]\n",
    "\n",
    "inner = (cq.Workplane('XY')\n",
    "               .workplane(offset=-L/2.0)\n",
    "               .dxf('downloads/profile.dxf')\n",
    "               .extrude(L)\n",
    "               # holes on the side which are\n",
    "               # used to mount the inner frame\n",
    "               # to the outer frame\n",
    "               .faces('>X').workplane()\n",
    "               .pushPoints(pnts)\n",
    "               .hole(tap_01875, depth=0.08)\n",
    "               # Access holes cut on wide face\n",
    "               # which will be facing inwards\n",
    "               # when the whole frame is assembled\n",
    "               .faces('>Y').workplane()\n",
    "               .pushPoints(pnts)\n",
    "               .rect(1.05, 0.5)\n",
    "               .cutBlind(-0.08)\n",
    "              )\n",
    "\n",
    "show_object(inner)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Inner Horizontals"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "show_object(inner_h)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Inner Verticals"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "show_object(inner_v)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Stands"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "L = 10.0\n",
    "\n",
    "stand = (cq.Workplane('XY')\n",
    "               .workplane(offset=-L/2.0)\n",
    "               .dxf('downloads/profile.dxf')\n",
    "               .extrude(L)\n",
    "               # hole on top for .25in bolt to pass through\n",
    "               .faces('>Y').workplane()\n",
    "               .hole(0.257, depth=0.08)\n",
    "               # Access hole on bottom\n",
    "               .faces('<Y').workplane()\n",
    "               .hole(0.9375, depth=0.08)\n",
    "              )\n",
    "\n",
    "show_object(stand)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Lock Bars"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "L = 19.6693 # comes from height of scrn + offset due to tube dims\n",
    "tap_025 = 0.201\n",
    "\n",
    "pnts = [(0.0, 0.0 ),\n",
    "        (0.0,  (L/2.0 - 3.0) ),\n",
    "        (0.0, -(L/2.0 - 3.0) )]\n",
    "\n",
    "end_holes = [( 0.5,  (L/2.0 - 0.25) ),\n",
    "             (-0.5,  (L/2.0 - 0.25) ),\n",
    "             ( 0.5, -(L/2.0 - 0.25) ),\n",
    "             (-0.5, -(L/2.0 - 0.25) )]\n",
    "\n",
    "lock_bar = (cq.Workplane('XY')\n",
    "               .workplane(offset=-L/2.0)\n",
    "               .dxf('downloads/profile.dxf')\n",
    "               .extrude(L)\n",
    "               # hole on bottom for .25in bolt\n",
    "               # to be threaded through for locking\n",
    "               .faces('<Y').workplane()\n",
    "               .pushPoints(pnts)\n",
    "               .hole(tap_025, depth=0.08)\n",
    "               # Access hole on top\n",
    "               .faces('>Y').workplane()\n",
    "               .pushPoints(pnts)\n",
    "               .hole(0.9375, depth=0.08)\n",
    "               # holes on ends for 3/16in \n",
    "               # screws to pass through\n",
    "               .faces('<Y').workplane()\n",
    "               .pushPoints(end_holes)\n",
    "               .hole(0.1875, depth=0.08)\n",
    "               # cut 45deg. triangles from\n",
    "               # tube ends for screw access\n",
    "               .faces('>X').workplane(centerOption='CenterOfBoundBox')\n",
    "               .moveTo(-0.25, (L/2.0) )\n",
    "               .polyline([( 0.25, (L/2.0) ),\n",
    "                          ( 0.25, (L/2.0) - 0.5 )]).close()\n",
    "               .cutThruAll()\n",
    "               .faces('>X').workplane(centerOption='CenterOfBoundBox')\n",
    "               .moveTo(-0.25, -(L/2.0) )\n",
    "               .polyline([( 0.25, -(L/2.0) ),\n",
    "                          ( 0.25, -(L/2.0) + 0.5 )]).close()\n",
    "               .cutThruAll()\n",
    "              )\n",
    "\n",
    "show_object(lock_bar)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Design Assembly\n",
    "\n",
    "This frame is a bit more complex of an assembly, so the following code might get a bit messy. It'll show off the intended design, though."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import cqjupyter_extras as cqe\n",
    "import cqtools\n",
    "\n",
    "# PARTS LIST\n",
    "# inner_h\n",
    "# inner_v\n",
    "# outer_h_bottom\n",
    "# outer_h_top\n",
    "# outer_v\n",
    "# stand\n",
    "# lock_bar\n",
    "\n",
    "# all positions are in mm.\n",
    "# There is definite need to improve the\n",
    "# assembly workflow here.\n",
    "asm = [ \n",
    "    ['stand', '0 0  186.4', '0 90 0' ],\n",
    "    ['stand', '0 0 -186.4', '0 90 0' ],\n",
    "    ['outer_h_bottom', '0 12.7 0', '0 0 0' ],\n",
    "    ['inner_h', '12.7 38.1 0', '0 0 90' ],\n",
    "    ['outer_v', '0 256.3 -395.95', '90 90 90' ],\n",
    "    ['inner_v', '12.7 256.3 -370.55', '270 90 0' ],\n",
    "    ['outer_v', '0 256.3 395.95', '270 90 270' ],\n",
    "    ['inner_v', '12.7 256.3 370.55', '90 270 0' ],\n",
    "    ['outer_h_top', '0 500.0 0', '180 0 0' ],\n",
    "    ['inner_h', '12.7 474.4 0', '0 0 90' ],\n",
    "    ['lock_bar', '-25.4 256.3 186.4', '90 270 0' ],\n",
    "    ['lock_bar', '-25.4 256.3 -186.4', '90 270 0' ],\n",
    "]\n",
    "\n",
    "# cqe.cqassemble(asm, name='assembly')\n",
    "# load the STEP files to build the .STEP assembly file\n",
    "inner_h = cqtools._loadSTEP('downloads/inner_h.STEP')\n",
    "inner_v = cqtools._loadSTEP('downloads/inner_v.STEP')\n",
    "outer_h_bottom = cqtools._loadSTEP('downloads/outer_h_bottom.STEP')\n",
    "outer_h_top = cqtools._loadSTEP('downloads/outer_h_top.STEP')\n",
    "outer_v = cqtools._loadSTEP('downloads/outer_v.STEP')\n",
    "stand = cqtools._loadSTEP('downloads/stand.STEP')\n",
    "lock_bar = cqtools._loadSTEP('downloads/lock_bar.STEP')\n",
    "\n",
    "asm2 = [\n",
    "    (stand\n",
    "         .rotate((0,0,0), (0,1,0), 90)\n",
    "         .translate((0, 0, 186.4))\n",
    "         .findSolid()\n",
    "    ),\n",
    "    (stand\n",
    "         .rotate((0,0,0), (0,1,0), 90)\n",
    "         .translate((0, 0, -186.4))\n",
    "         .findSolid()\n",
    "    ),\n",
    "    (outer_h_bottom\n",
    "         .rotate((0,0,0), (1,0,0), 0)\n",
    "         .translate((0, 12.7, 0))\n",
    "         .findSolid()\n",
    "    ),\n",
    "    (inner_h\n",
    "         .rotate((0,0,0), (0,0,1), 90)\n",
    "         .rotate((0,0,0), (1,0,0), 180)\n",
    "         .translate((12.7, 38.1, 0))\n",
    "         .findSolid()\n",
    "    ),\n",
    "    (outer_v\n",
    "         .rotate((0,0,0), (1,0,0), 270)\n",
    "         .rotate((0,0,0), (0,0,1), 180)\n",
    "         .translate((0, 256.3, -395.95))\n",
    "         .findSolid()\n",
    "    ),\n",
    "    (inner_v\n",
    "         .rotate((0,0,0), (0,0,1), 90)\n",
    "         .rotate((0,0,0), (1,0,0), 270)\n",
    "         .translate((12.7, 256.3, -370.55))\n",
    "         .findSolid()\n",
    "    ),\n",
    "    (outer_v\n",
    "         .rotate((0,0,0), (1,0,0), 90)\n",
    "         .rotate((0,0,0), (0,0,1), 180)\n",
    "         .translate((0, 256.3, 395.95))\n",
    "         .findSolid()\n",
    "    ),\n",
    "    (inner_v\n",
    "         .rotate((0,0,0), (0,0,1), 90)\n",
    "         .rotate((0,0,0), (1,0,0), 90)\n",
    "         .translate((12.7, 256.3, 370.55))\n",
    "         .findSolid()\n",
    "    ),\n",
    "    (outer_h_top\n",
    "         .rotate((0,0,0), (1,0,0), 180)\n",
    "         .translate((0, 500.0, 0))\n",
    "         .findSolid()\n",
    "    ),\n",
    "    (inner_h\n",
    "         .rotate((0,0,0), (0,0,1), 90)\n",
    "         .translate((12.7, 474.4, 0))\n",
    "         .findSolid()\n",
    "    ),\n",
    "    (lock_bar\n",
    "         .rotate((0,0,0), (0,0,1), 90)\n",
    "         .rotate((0,0,0), (1,0,0), 270)\n",
    "         .translate((-25.4, 256.3, 186.4))\n",
    "         .findSolid()\n",
    "    ),\n",
    "    (lock_bar\n",
    "         .rotate((0,0,0), (0,0,1), 90)\n",
    "         .rotate((0,0,0), (1,0,0), 270)\n",
    "         .translate((-25.4, 256.3, -186.4))\n",
    "         .findSolid()\n",
    "    ),\n",
    "]\n",
    "\n",
    "# Some weird syntax to properly create the compound geometry\n",
    "# There is likely a cleaner way to do this, but I'm unaware currently\n",
    "final = cq.cq.Compound.makeCompound(asm2)\n",
    "assembly = cq.CQ(final)\n",
    "show_object(assembly)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<iframe width=\"650\" height=\"500\" src=\"assembly.html?overflow=none\" frameborder=\"0\" allowfullscreen=\"\"></iframe>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Building it for Real\n",
    "\n",
    "Once again I find myself kicking the laser tube cutter into action. I'm extremely lucky to remember how this thing works. As it turns out, I need to be good at last second maintenance for this thing. I had to search the shop for some hydraulic oil to top up the reservoir! Fortunately, everything still works.\n",
    "\n",
    "<center><video style=\"margin-left: 0;\" width=\"300\" height=\"300\" autoplay=\"\" muted=\"\" loop=\"\" controls=\"\">\n",
    "  <source src=\"img/cutting.mp4\" type=\"video/mp4\">\n",
    "</video></center>\n",
    "\n",
    "With all the parts cut, it simply comes down to assembly. The pictures below show the process, more or less. Of course, the struggle of tapping the holes and tightening up all of the screws is not pictured.\n",
    "\n",
    "<iframe width=\"650\" height=\"700\" src=\"img/asm_imgs.html?overflow=none\" frameborder=\"0\" allowfullscreen></iframe>\n",
    "\n",
    "And, just for fun, here's one final shot of my TV, quietly assisting me in enjoying some Nintendo Switch gaming.\n",
    "\n",
    "![](img/final.jpg)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Final Thoughts\n",
    "\n",
    "I can finally use my TV again. Mission accomplished! I like the industrial look to the whole thing, too; I suspect there's no TV quite like this one.\n",
    "\n",
    "Yet as always, there is room for improvement.\n",
    "\n",
    "### Process Improvements\n",
    "\n",
    "* tapping holes makes for some nice construction, but is tedious to do. Reduce how many bolted connections are needed to reduce this.\n",
    "* it might be good to include more hand-drawn sketch images in these notebooks, to convey the initial thinking phases of my design work. I could alternatively create some basic 2D layout drawings in .dxf format. With that, I could potentially have some fancy import functions that semi-automatically place 3D objects according to some layout drawing. Lot's of potential there, for sure.\n",
    "\n",
    "### Design Improvements\n",
    "\n",
    "* I cut 5 holes for screws in every side. I tried using only 3 holes, and it held things together perfectly, so there was no need for so much cutting.\n",
    "* The 0.5in 'lip' added to the TV does *slightly* interfere with the image when viewing at extreme angles. That fact paired with the reflectivity of the surface can cause some distraction. I only view casually anyway, so this doesn't bother me. It's definitely not good enough for the average consumer, though.\n",
    "* Finishing. I like the industrial look, but it could be out of place in most homes. A nice powder coated finish could look really sharp.\n",
    "* Weight. This thing is **heavy**. I like it that way, but it's certainly excessive. I could strategically cut holes on all inner faces to drastically cut down weight. Or I could make a triangular cut out pattern part of the aesthetic of the frame. As well, I could re-think the front frame portion as a flat sheet or even as a piece of plastic or wood to cut down a lot of weight.\n",
    "* don't forget the remote! I forgot that the only way to turn the TV on is via the remote control (power button was attached to the old bezel). You can't shoot IR signals through solid metal, so I had to drill a hole that aligns with the sensor. Silly thing to forget.\n",
    "    \n",
    "There it is, my design and build of an industrial-strength TV frame. Thanks for reading through my article. If you have any questions or suggestions, I'm glad to listen! Please ask away on my Twitter, [@RustyVermeer](https://www.twitter.com/RustyVermeer)."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Bits and Pieces\n",
    "\n",
    "## Software\n",
    "\n",
    "I used several different programs to make this project:\n",
    "* [CadQuery Github Page](https://github.com/dcowden/cadquery/tree/9e18b61d645981395e20fa62afd0861e023b865c)\n",
    "* [FreeCAD](https://www.freecadweb.org/)\n",
    "* [Jupyter](http://jupyter.org/)\n",
    "* [CQNB - Jupyter Notebook CadQuery Extension](https://github.com/RustyVermeer/cqnb)\n",
    "* [A-Frame VR](https://aframe.io/)\n",
    "\n",
    "\n",
    "## Downloads\n",
    "\n",
    "As mentioned at the start of this post, I've got some downloads for you to look at.\n",
    "\n",
    "* <a href=\"downloads/step-files.zip\" download>step-files.zip</a> containing:\n",
    "    * .STEP files for each part\n",
    "    * .STEP file for the assembly\n",
    "    * the CQ code as a .py file, which can be run locally (requires FreeCAD and CadQuery) --> Please don't trust me blindly, read the code before you run things.\n",
    "    * the .ipynb file (Jupyter Notebook) that this post is built from. You can run this on your own Jupyter server, but once again FreeCAD and CadQuery are required. Additionally, the cqjupyter module is needed to be able to view your models in the notebook.\n",
    "* <a href=\"downloads/tv_frame.ipynb\" download>ipad_stand.ipynb</a> which I created as I went through my design process. It also happens to be the source (more or less) of this post.\n",
    "* <a href=\"downloads/tv_frame.py\" download>ipad_stand.py</a>. The source code for the cadquery parts, with no additional markdown nonsense. You'll need to look at the CadQuery documentation to set things up, if you don't already have it installed."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[NbConvertApp] Converting notebook tv_frame.ipynb to markdown\n",
      "[NbConvertApp] Writing 19501 bytes to tv_frame.md\n",
      "Created index.html\n"
     ]
    }
   ],
   "source": [
    "!jupyter nbconvert --to markdown tv_frame.ipynb\n",
    "\n",
    "import page_tools as pg\n",
    "pg.generate_page('tv_frame', color='#858a7e')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
